# This is a basic workflow to help you get started with Actions

name: Generate hugo and publish preview site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ r03-start ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.66.0'

    - name: Build
      run: hugo

    - name: Delete Ignore Files #delete ignore contents
      run: rm -rf inquiry lib contents/h28 contents/h29 contents/h30
      working-directory: public

    - name: Delete Old Files #delete ignore contents
      run: find . -mtime 10
      working-directory: public

    - name: Delete Old Files #delete ignore contents
      run: find . -mtime 10 -exec rm -f {} \;
      working-directory: public

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://sendai-tta.sakura.ne.jp/home/sendai-tta/www/sendai-tta_preview
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
